apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: purecloud75/hostservice:225ae298391c37265c823f0caec9072cae3ad679
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
